# Remerciements plus des bricoles {.unnumbered}

Ceci est la version en ligne du pdf [disponible sur HAL](https://hal.science/hal-04052709/document). Manquent ici la tables des figures, l'index des noms propres et une poignée de coquilles.

J'avais prévu de faire relire ce guide pratique avant de le mettre en ligne et je n'ai pas osé déranger les collègues dont la majorité est sous l'eau, débordée et/ou en *burn-out* chronique - j'ai tout de même demandé une relecture pour les annexes mathématiques à mon frère, un grand merci Pierre ! J'espère n'avoir pas écrit trop de bêtises ni laissé traîner trop de coquilles. Ce guide doit beaucoup aux différentes collègues avec lesquelles j'ai eu le plaisir d'animer des formations ces dernières années, notamment, par ordre alphabétique, Fabien Eloire, Violaine Jurie, Karine Karila-Cohen, Claire Lemercier, Rosemonde Letricot, Marion Maisonobe, Silvia Marzagalli, Pierre Mercklé, Hugues Pecout et Isabelle Rosé. Ce guide n'existerait pas si nous n'avions pas fondé en 2010 le groupe fmr (flux, matrices, réseaux) avec César Ducruet : un grand merci à toi et au "noyau dur historique" (Françoise, Marion, Matthieu et Serge). Merci aussi à François Briatte pour le [*Awesome Network Analysis*](https://github.com/briatte/awesome-network-analysis) et pour les découvertes musicales (Olhava !). Iels ne sont évidemment pas responsables des approximations et des formules à l'emporte-pièce présentes dans ce texte.

En 2023, on continue à lire des appels pour des journées/salons/forums des "doctorants" ou des calendriers concernant les concours "chercheurs". Ça m'agace. Donc ce texte, comme plusieurs de mes textes récents, est exclusivement écrit au féminin ; la seule exception concerne les communautés scientifiques exclusivement masculines évoquées dans le [chapitre @sec-Chistoires].

Ce guide pratique est entièrement libre et gratuit. Fonctionnaire payé par l'argent public, j'estime que mon travail doit accessible à toute personne intéressée. Et que je ne suis pas là pour rapporter des sous à quelque éditeur que ce soit. Ce qui ne vous dispense pas, si ce guide vous est utile, de le citer dans vos travaux. Comme ça par exemple :

Laurent Beauguitte, 2023, *L'analyse de réseau en sciences sociales. Petit guide pratique*. Groupe fmr, <https://hal.science/hal-04052709>.

Si vous repérez des erreurs, n'hésitez pas à me les signaler en commentant le billet dédié sur le carnet de recherche du groupe fmr ([L'AR en sciences sociales. Petit guide pratique - SAV](https://groupefmr.hypotheses.org/6189)). Si la lecture de certains chapitres ne vous satisfait pas totalement (ce qui est mon cas...), si vous avez l'impression qu'il manque des éléments, que je passe trop vite sur certains aspects, si vous aimeriez que telle méthode soit abordée, etc. etc. surtout, surtout, n'hésitez pas à me le signaler. Une version 1 verra sans doute le jour prochainement.
